<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><Nullable>disable</Nullable><ImplicitUsings>enable</ImplicitUsings><PlatformTarget>x64</PlatformTarget></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\sf2\SoulsFormats\SoulsFormats.csproj" /></ItemGroup>
</Project>
